"""Deterministic runtime primitives."""

from .storage import (
    AppendOnlyStore,
    ArtifactTypeMismatchError,
    DuplicateArtifactIdError,
    DuplicateEventIdError,
    IntegrityError,
    canonical_content_hash,
    canonical_json_bytes,
    with_content_hash,
)
from .references import (
    ARTIFACT_REFERENCE_FAILURE_RESOLUTION,
    ARTIFACT_REFERENCE_INVARIANT,
    ArtifactReferenceResolver,
    ReferenceFailure,
    ReferenceFailureCode,
    ReferenceResolution,
    ResolvedArtifact,
)
from .contracts import ContractValidationError, validate_contract
from .reducer import (
    IllegalTransitionError,
    ReducerError,
    canonical_state_bytes,
    reduce_event,
    replay_events,
)
from .preexecution import (
    Criticality,
    ReconciliationEvidence,
    Resolution,
    ValidationOutcome,
    ValidatorStatus,
    Verdict,
    adapter_compatibility_check,
    compensation_prevalidation_check,
    current_version_check,
    reconcile_decision,
)
from .projection import (
    POLICY_VISIBLE,
    PROTECTED_ACCESS_CLASSES,
    AccessBoundaryError,
    ObservationProjection,
    ProjectionError,
    ProjectionLineageEntry,
    ProjectionSourceError,
    project_observation,
)

__all__ = [
    "AppendOnlyStore",
    "ArtifactTypeMismatchError",
    "ARTIFACT_REFERENCE_FAILURE_RESOLUTION",
    "ARTIFACT_REFERENCE_INVARIANT",
    "ArtifactReferenceResolver",
    "DuplicateArtifactIdError",
    "DuplicateEventIdError",
    "IntegrityError",
    "IllegalTransitionError",
    "AccessBoundaryError",
    "ObservationProjection",
    "POLICY_VISIBLE",
    "PROTECTED_ACCESS_CLASSES",
    "ProjectionError",
    "ProjectionLineageEntry",
    "ProjectionSourceError",
    "ReferenceFailure",
    "ReferenceFailureCode",
    "ReferenceResolution",
    "ResolvedArtifact",
    "ReducerError",
    "SchemaValidationError",
    "ContractValidationError",
    "validate_contract",
    "canonical_content_hash",
    "canonical_json_bytes",
    "canonical_state_bytes",
    "reduce_event",
    "replay_events",
    "project_observation",
    "with_content_hash",
    "Criticality",
    "ReconciliationEvidence",
    "Resolution",
    "ValidationOutcome",
    "ValidatorStatus",
    "Verdict",
    "adapter_compatibility_check",
    "compensation_prevalidation_check",
    "current_version_check",
    "reconcile_decision",
]
