"""Deterministic runtime primitives."""

from .storage import (
    AppendOnlyStore,
    ArtifactTypeMismatchError,
    DuplicateArtifactIdError,
    DuplicateEventIdError,
    IntegrityError,
    canonical_content_hash,
    canonical_json_bytes,
    with_content_hash,
)
from .references import (
    ARTIFACT_REFERENCE_FAILURE_RESOLUTION,
    ARTIFACT_REFERENCE_INVARIANT,
    ArtifactReferenceResolver,
    ReferenceFailure,
    ReferenceFailureCode,
    ReferenceResolution,
    ResolvedArtifact,
)
from .contracts import ContractValidationError, validate_contract
from .reducer import (
    IllegalTransitionError,
    ReducerError,
    SchemaValidationError,
    canonical_state_bytes,
    reduce_event,
    replay_events,
)
from .preexecution import (
    Criticality,
    InvariantDisposition,
    ReconciliationEvidence,
    Resolution,
    ValidationOutcome,
    ValidatorStatus,
    Verdict,
    adapter_compatibility_check,
    compensation_prevalidation_check,
    current_version_check,
    reconcile_decision,
)
from .projection import (
    POLICY_VISIBLE,
    PROTECTED_ACCESS_CLASSES,
    AccessBoundaryError,
    ObservationProjection,
    ProjectionError,
    ProjectionLineageEntry,
    ProjectionSourceError,
    project_observation,
)
from .ingest import (
    INGEST_FAILURE_RESOLUTION,
    INGEST_VALIDATORS,
    artifact_integrity_check,
    artifact_reference_check,
    event_id_uniqueness_check,
    policy_input_leakage_check,
)
from .replay_invariants import (
    REPLAY_FAILURE_RESOLUTION,
    REPLAY_INVARIANT_VALIDATORS,
    deterministic_replay_check,
    episode_trace_order_check,
    logical_clock_order_check,
    state_version_transition_check,
)
from .thanksgiving import (
    Criticality as EnvironmentCriticality,
    Enforceability,
    EnvironmentConstraintError,
    ThanksgivingEpisode,
    evaluate_schedule,
    initial_thanksgiving_state,
    run_thanksgiving_episode,
    thanksgiving_actions,
)

__all__ = [
    "AppendOnlyStore",
    "ArtifactTypeMismatchError",
    "ARTIFACT_REFERENCE_FAILURE_RESOLUTION",
    "ARTIFACT_REFERENCE_INVARIANT",
    "ArtifactReferenceResolver",
    "DuplicateArtifactIdError",
    "DuplicateEventIdError",
    "IntegrityError",
    "IllegalTransitionError",
    "AccessBoundaryError",
    "ObservationProjection",
    "POLICY_VISIBLE",
    "PROTECTED_ACCESS_CLASSES",
    "ProjectionError",
    "ProjectionLineageEntry",
    "ProjectionSourceError",
    "ReferenceFailure",
    "ReferenceFailureCode",
    "ReferenceResolution",
    "ResolvedArtifact",
    "ReducerError",
    "SchemaValidationError",
    "ContractValidationError",
    "validate_contract",
    "canonical_content_hash",
    "canonical_json_bytes",
    "canonical_state_bytes",
    "reduce_event",
    "replay_events",
    "project_observation",
    "with_content_hash",
    "Criticality",
    "InvariantDisposition",
    "ReconciliationEvidence",
    "Resolution",
    "ValidationOutcome",
    "ValidatorStatus",
    "Verdict",
    "REPLAY_FAILURE_RESOLUTION",
    "REPLAY_INVARIANT_VALIDATORS",
    "deterministic_replay_check",
    "episode_trace_order_check",
    "logical_clock_order_check",
    "state_version_transition_check",
    "adapter_compatibility_check",
    "compensation_prevalidation_check",
    "current_version_check",
    "reconcile_decision",
    "INGEST_FAILURE_RESOLUTION",
    "INGEST_VALIDATORS",
    "artifact_integrity_check",
    "artifact_reference_check",
    "event_id_uniqueness_check",
    "policy_input_leakage_check",
    "EnvironmentCriticality",
    "Enforceability",
    "EnvironmentConstraintError",
    "ThanksgivingEpisode",
    "evaluate_schedule",
    "initial_thanksgiving_state",
    "run_thanksgiving_episode",
    "thanksgiving_actions",
]
